# Generated by Django 5.1.7 on 2026-01-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminstitution',
            name='billing_packages',
            field=models.ManyToManyField(related_name='system_institutions', through='billing.SystemInsitutionBillingPackage', to='billing.billingpackage'),
        ),
    ]
